<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        cota
* GENERATION DATE:  12.10.2006
* CLASS FILE:       C:\Develop\xampp\htdocs\sql_class_generator/generated_classes/class.cota.php
* FOR MYSQL TABLE:  cota
* FOR MYSQL DB:     officemkt
* -------------------------------------------------------
* CODE GENERATED BY:
* MY PHP-MYSQL-CLASS GENERATOR
* from: >> www.voegeli.li >> (download for free!)
* -------------------------------------------------------
*
*/

include_once("class.database.php");

// **********************
// CLASS DECLARATION
// **********************

class Cota
{ // class : begin


// **********************
// ATTRIBUTE DECLARATION
// **********************

private $ID;   // KEY ATTR. WITH AUTOINCREMENT

private $EVEN_ID;   // (normal Attribute)
private $ORGA_ID;   // (normal Attribute)
private $STATUS;   // (normal Attribute)
private $DESCRICAO;   // (normal Attribute)
private $VALOR_TABELA;   // (normal Attribute)
private $VALOR_FECHADO;   // (normal Attribute)
private $DATA_FECHADO;   // (normal Attribute)
private $OBS;   // (normal Attribute)

private $database; // Instance of class database


// **********************
// CONSTRUCTOR METHOD
// **********************

function Cota()
{

$this->database = new Database();

}


// **********************
// GETTER METHODS
// **********************


function getID()
{
return $this->ID;
}

function getEVEN_ID()
{
return $this->EVEN_ID;
}

function getORGA_ID()
{
return $this->ORGA_ID;
}

function getSTATUS()
{
return $this->STATUS;
}

function getDESCRICAO()
{
return $this->DESCRICAO;
}

function getVALOR_TABELA()
{
return $this->VALOR_TABELA;
}

function getVALOR_FECHADO()
{
return $this->VALOR_FECHADO;
}

function getDATA_FECHADO()
{
return $this->DATA_FECHADO;
}

function getOBS()
{
return $this->OBS;
}

// **********************
// SETTER METHODS
// **********************


function setID($val)
{
$this->ID =  $val;
}

function setEVEN_ID($val)
{
$this->EVEN_ID =  $val;
}

function setORGA_ID($val)
{
$this->ORGA_ID =  $val;
}

function setSTATUS($val)
{
$this->STATUS =  $val;
}

function setDESCRICAO($val)
{
$this->DESCRICAO =  $val;
}

function setVALOR_TABELA($val)
{
$this->VALOR_TABELA =  $val;
}

function setVALOR_FECHADO($val)
{
$this->VALOR_FECHADO =  $val;
}

function setDATA_FECHADO($val)
{
$this->DATA_FECHADO =  $val;
}

function setOBS($val)
{
$this->OBS =  $val;
}

// **********************
// SELECT METHOD / LOAD
// **********************

function select($id)
{

$sql =  "SELECT * FROM cota WHERE COTA_ID = $id;";
$result =  $this->database->query($sql);
$result = $this->database->result;
$row = mysql_fetch_object($result);


$this->ID = $row->COTA_ID;

$this->EVEN_ID = $row->EVEN_ID;

$this->ORGA_ID = $row->ORGA_ID;

$this->STATUS = $row->COTA_STATUS;

$this->DESCRICAO = $row->COTA_DESCRICAO;

$this->VALOR_TABELA = $row->COTA_VALOR_TABELA;

$this->VALOR_FECHADO = $row->COTA_VALOR_FECHADO;

$this->DATA_FECHADO = $row->COTA_DATA_FECHADO;

$this->OBS = $row->COTA_OBS;

}

// **********************
// DELETE
// **********************

function delete($id)
{
$sql = "DELETE FROM cota WHERE COTA_ID = $id;";
$result = $this->database->query($sql);

}

// **********************
// SAVE
// **********************

function save() {
	if ($this->ID != null) {
		$this->update($this->ID);
	} else {
		$this->insert();
	}
}

// **********************
// INSERT
// **********************

function insert()
{
$this->ID = ""; // clear key for autoincrement

$sql = "INSERT INTO cota ( EVEN_ID,ORGA_ID,COTA_STATUS,COTA_DESCRICAO,COTA_VALOR_TABELA,COTA_VALOR_FECHADO,COTA_DATA_FECHADO,COTA_OBS ) VALUES ( '$this->EVEN_ID','$this->ORGA_ID','$this->STATUS','$this->DESCRICAO','$this->VALOR_TABELA','$this->VALOR_FECHADO','$this->DATA_FECHADO','$this->OBS' )";
$result = $this->database->query($sql);
$this->ID = mysql_insert_id($this->database->link);

}

// **********************
// UPDATE
// **********************

function update($id)
{



$sql = " UPDATE cota SET  EVEN_ID = '$this->EVEN_ID',ORGA_ID = '$this->ORGA_ID',COTA_STATUS = '$this->STATUS',COTA_DESCRICAO = '$this->DESCRICAO',COTA_VALOR_TABELA = '$this->VALOR_TABELA',COTA_VALOR_FECHADO = '$this->VALOR_FECHADO',COTA_DATA_FECHADO = '$this->DATA_FECHADO',COTA_OBS = '$this->OBS' WHERE COTA_ID = $id ";

$result = $this->database->query($sql);



}


} // class : end

?>