<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        parcela
* GENERATION DATE:  12.10.2006
* CLASS FILE:       C:\Develop\xampp\htdocs\sql_class_generator/generated_classes/class.parcela.php
* FOR MYSQL TABLE:  cota_parcela
* FOR MYSQL DB:     officemkt
* -------------------------------------------------------
* CODE GENERATED BY:
* MY PHP-MYSQL-CLASS GENERATOR
* from: >> www.voegeli.li >> (download for free!)
* -------------------------------------------------------
*
*/

include_once("class.database.php");

// **********************
// CLASS DECLARATION
// **********************

class Parcela
{ // class : begin


// **********************
// ATTRIBUTE DECLARATION
// **********************

private $ID;   // KEY ATTR. WITH AUTOINCREMENT

private $COTA_ID;   // (normal Attribute)
private $DATA_PREVISTA;   // (normal Attribute)
private $DATA_PAGA;   // (normal Attribute)
private $VALOR;   // (normal Attribute)
private $STATUS;   // (normal Attribute)

private $database; // Instance of class database


// **********************
// CONSTRUCTOR METHOD
// **********************

function Parcela()
{

$this->database = new Database();

}


// **********************
// GETTER METHODS
// **********************


function getID()
{
return $this->ID;
}

function getCOTA_ID()
{
return $this->COTA_ID;
}

function getDATA_PREVISTA()
{
return $this->DATA_PREVISTA;
}

function getDATA_PAGA()
{
return $this->DATA_PAGA;
}

function getVALOR()
{
return $this->VALOR;
}

function getSTATUS()
{
return $this->STATUS;
}

// **********************
// SETTER METHODS
// **********************


function setID($val)
{
$this->ID =  $val;
}

function setCOTA_ID($val)
{
$this->COTA_ID =  $val;
}

function setDATA_PREVISTA($val)
{
$this->DATA_PREVISTA =  $val;
}

function setDATA_PAGA($val)
{
$this->DATA_PAGA =  $val;
}

function setVALOR($val)
{
$this->VALOR =  $val;
}

function setSTATUS($val)
{
$this->STATUS =  $val;
}

// **********************
// SELECT METHOD / LOAD
// **********************

function select($id)
{

$sql =  "SELECT * FROM cota_parcela WHERE PARC_ID = $id;";
$result =  $this->database->query($sql);
$result = $this->database->result;
$row = mysql_fetch_object($result);


$this->ID = $row->PARC_ID;

$this->COTA_ID = $row->COTA_ID;

$this->DATA_PREVISTA = $row->PARC_DATA_PREVISTA;

$this->DATA_PAGA = $row->PARC_DATA_PAGA;

$this->VALOR = $row->PARC_VALOR;

$this->STATUS = $row->PARC_STATUS;

}

// **********************
// DELETE
// **********************

function delete($id)
{
$sql = "DELETE FROM cota_parcela WHERE PARC_ID = $id;";
$result = $this->database->query($sql);

}

// **********************
// SAVE
// **********************

function save() {
	if ($this->ID != null) {
		$this->update($this->ID);
	} else {
		$this->insert();
	}
}


// **********************
// INSERT
// **********************

function insert()
{
$this->ID = ""; // clear key for autoincrement

$sql = "INSERT INTO cota_parcela ( COTA_ID,PARC_DATA_PREVISTA,PARC_DATA_PAGA,PARC_VALOR,PARC_STATUS ) VALUES ( '$this->COTA_ID','$this->DATA_PREVISTA','$this->DATA_PAGA','$this->VALOR','$this->STATUS' )";
$result = $this->database->query($sql);
$this->ID = mysql_insert_id($this->database->link);

}

// **********************
// UPDATE
// **********************

function update($id)
{



$sql = " UPDATE cota_parcela SET  COTA_ID = '$this->COTA_ID',PARC_DATA_PREVISTA = '$this->DATA_PREVISTA',PARC_DATA_PAGA = '$this->DATA_PAGA',PARC_VALOR = '$this->VALOR',PARC_STATUS = '$this->STATUS' WHERE PARC_ID = $id ";

$result = $this->database->query($sql);



}


} // class : end

?>