<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        pessoa
* GENERATION DATE:  12.10.2006
* CLASS FILE:       C:\Develop\xampp\htdocs\sql_class_generator/generated_classes/class.pessoa.php
* FOR MYSQL TABLE:  pessoa
* FOR MYSQL DB:     officemkt
* -------------------------------------------------------
* CODE GENERATED BY:
* MY PHP-MYSQL-CLASS GENERATOR
* from: >> www.voegeli.li >> (download for free!)
* -------------------------------------------------------
*
*/

include_once("class.database.php");

// **********************
// CLASS DECLARATION
// **********************

class Pessoa
{ // class : begin


// **********************
// ATTRIBUTE DECLARATION
// **********************

private $ID;   // KEY ATTR. WITH AUTOINCREMENT

private $ORGA_ID;   // (normal Attribute)
private $TRATAMENTO;   // (normal Attribute)
private $NOME;   // (normal Attribute)
private $EMAIL;   // (normal Attribute)
private $FONE;   // (normal Attribute)
private $CELULAR;   // (normal Attribute)
private $NASCIMENTO;   // (normal Attribute)
private $SEXO;   // (normal Attribute)
private $OBS;   // (normal Attribute)

private $database; // Instance of class database


// **********************
// CONSTRUCTOR METHOD
// **********************

function Pessoa()
{

$this->database = new Database();

}


// **********************
// GETTER METHODS
// **********************


function getID()
{
return $this->ID;
}

function getORGA_ID()
{
return $this->ORGA_ID;
}

function getTRATAMENTO()
{
return $this->TRATAMENTO;
}

function getNOME()
{
return $this->NOME;
}

function getEMAIL()
{
return $this->EMAIL;
}

function getFONE()
{
return $this->FONE;
}

function getCELULAR()
{
return $this->CELULAR;
}

function getNASCIMENTO()
{
return $this->NASCIMENTO;
}

function getSEXO()
{
return $this->SEXO;
}

function getOBS()
{
return $this->OBS;
}

// **********************
// SETTER METHODS
// **********************


function setID($val)
{
$this->ID =  $val;
}

function setORGA_ID($val)
{
$this->ORGA_ID =  $val;
}

function setTRATAMENTO($val)
{
$this->TRATAMENTO =  $val;
}

function setNOME($val)
{
$this->NOME =  $val;
}

function setEMAIL($val)
{
$this->EMAIL =  $val;
}

function setFONE($val)
{
$this->FONE =  $val;
}

function setCELULAR($val)
{
$this->CELULAR =  $val;
}

function setNASCIMENTO($val)
{
$this->NASCIMENTO =  $val;
}

function setSEXO($val)
{
$this->SEXO =  $val;
}

function setOBS($val)
{
$this->OBS =  $val;
}

// **********************
// SELECT METHOD / LOAD
// **********************

function select($id)
{

$sql =  "SELECT * FROM pessoa WHERE PESS_ID = $id;";
$result =  $this->database->query($sql);
$result = $this->database->result;
$row = mysql_fetch_object($result);


$this->ID = $row->PESS_ID;
$this->ORGA_ID = $row->ORGA_ID;
$this->TRATAMENTO = $row->PESS_TRATAMENTO;
$this->NOME = $row->PESS_NOME;
$this->EMAIL = $row->PESS_EMAIL;
$this->FONE = $row->PESS_FONE;
$this->CELULAR = $row->PESS_CELULAR;
$this->NASCIMENTO = $row->PESS_NASCIMENTO;
$this->SEXO = $row->PESS_SEXO;
$this->OBS = $row->PESS_OBS;

}

// **********************
// DELETE
// **********************

function delete($id)
{
$sql = "DELETE FROM pessoa WHERE PESS_ID = $id;";
$result = $this->database->query($sql);

}

// **********************
// SAVE
// **********************

function save() {
	if ($this->ID != null) {
		$this->update($this->ID);
	} else {
		$this->insert();
	}
}


// **********************
// INSERT
// **********************

function insert()
{
$this->ID = ""; // clear key for autoincrement

$sql = "INSERT INTO pessoa ( ORGA_ID,PESS_TRATAMENTO,PESS_NOME,PESS_EMAIL,PESS_FONE,PESS_CELULAR,PESS_NASCIMENTO,PESS_SEXO,PESS_OBS ) VALUES ( '$this->ORGA_ID','$this->TRATAMENTO','$this->NOME','$this->EMAIL','$this->FONE','$this->CELULAR','$this->NASCIMENTO','$this->SEXO','$this->OBS' )";
$result = $this->database->query($sql);
$this->ID = mysql_insert_id($this->database->link);

}

// **********************
// UPDATE
// **********************

function update($id)
{



$sql = " UPDATE pessoa SET  ORGA_ID = '$this->ORGA_ID',PESS_TRATAMENTO = '$this->TRATAMENTO',PESS_NOME = '$this->NOME',PESS_EMAIL = '$this->EMAIL',PESS_FONE = '$this->FONE',PESS_CELULAR = '$this->CELULAR',PESS_NASCIMENTO = '$this->NASCIMENTO',PESS_SEXO = '$this->SEXO',PESS_OBS = '$this->OBS' WHERE PESS_ID = $id ";

$result = $this->database->query($sql);



}


} // class : end

?>