<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        configuracao
* GENERATION DATE:  12.10.2006
* CLASS FILE:       C:\Develop\xampp\htdocs\sql_class_generator/generated_classes/class.configuracao.php
* FOR MYSQL TABLE:  evento_configuracao
* FOR MYSQL DB:     officemkt
* -------------------------------------------------------
* CODE GENERATED BY:
* MY PHP-MYSQL-CLASS GENERATOR
* from: >> www.voegeli.li >> (download for free!)
* -------------------------------------------------------
*
*/

include_once("class.database.php");

// **********************
// CLASS DECLARATION
// **********************

class Configuracao { // class : begin


// **********************
// ATTRIBUTE DECLARATION
// **********************

private $EVEN_ID;   // KEY ATTR. WITH AUTOINCREMENT
private $ALIAS;
private $LOGO_FORMATO;   // (normal Attribute)
private $DADOS_RECIBO;   // (normal Attribute)

private $database; // Instance of class database


// **********************
// CONSTRUCTOR METHOD
// **********************

function Configuracao() {

$this->database = new Database();

}


// **********************
// GETTER METHODS
// **********************


function getEVEN_ID() {
return $this->EVEN_ID;
}

function getALIAS() {
return $this->ALIAS;
}

function getLOGO_FORMATO() {
return $this->LOGO_FORMATO;
}

function getDADOS_RECIBO() {
return $this->DADOS_RECIBO;
}




// **********************
// SETTER METHODS
// **********************


function setEVEN_ID($val) {
$this->EVEN_ID =  $val;
}

function setALIAS($val) {
$this->ALIAS =  $val;
}

function setLOGO_FORMATO($val) {
$this->LOGO_FORMATO =  $val;
}

function setDADOS_RECIBO($val) {
$this->DADOS_RECIBO =  $val;
}



// **********************
// SELECT METHOD / LOAD
// **********************

function select($id) {

$sql =  "SELECT * FROM evento_configuracao WHERE EVEN_ID = $id;";
$result =  $this->database->query($sql);
$result = $this->database->result;
$row = mysql_fetch_object($result);

$this->EVEN_ID = $row->EVEN_ID;
$this->ALIAS = $row->CONF_ALIAS;
$this->LOGO_FORMATO = $row->CONF_LOGO_FORMATO;
$this->DADOS_RECIBO = $row->CONF_DADOS_RECIBO;



}

// **********************
// DELETE
// **********************

function delete($id) {
$sql = "DELETE FROM evento_configuracao WHERE EVEN_ID = $id;";
$result = $this->database->query($sql);

}

// **********************
// SAVE
// **********************

function save() {
	if ($this->EVEN_ID != null) {
		$this->update($this->EVEN_ID);
	} else {
		$this->insert();
	}
}

// **********************
// INSERT
// **********************

function insert() {
//$this->EVEN_ID = ""; // clear key for autoincrement

$sql = "INSERT INTO evento_configuracao (EVEN_ID, CONF_ALIAS, CONF_LOGO_FORMATO,CONF_DADOS_RECIBO) VALUES ($this->EVEN_ID,'$this->ALIAS','$this->LOGO_FORMATO','$this->DADOS_RECIBO')";
$result = $this->database->query($sql);
//$this->EVEN_ID = mysql_insert_id($this->database->link);

}

// **********************
// UPDATE
// **********************

function update($id) {

$sql = " UPDATE evento_configuracao SET CONF_ALIAS = '$this->ALIAS',CONF_LOGO_FORMATO = '$this->LOGO_FORMATO',CONF_DADOS_RECIBO = '$this->DADOS_RECIBO' WHERE EVEN_ID = $id ";

$result = $this->database->query($sql);

}


function updateLogo($filePath) {
	$fp      = fopen($filePath, 'r');
	$content = fread($fp, filesize($filePath));
	$content = addslashes($content);
	fclose($fp);
	$sql = ' UPDATE evento_configuracao SET CONF_LOGO = "'.$content.'" WHERE EVEN_ID = '.$this->getEVEN_ID() ;
	//echo $sql;break;
	$result = $this->database->query($sql);
	
}


function loadLogo() {
	
	$sql = ' SELECT CONF_LOGO FROM evento_configuracao WHERE EVEN_ID = '.$this->getEVEN_ID() ;
	//echo $sql."<br>";
	$result = $this->database->query($sql);
	$result = $this->database->result;
	$row = mysql_fetch_object($result);
	//echo $row->CONF_LOGO;break;
	
	return $row->CONF_LOGO;


}

function dumpLogo($filePath) {

	$filePath = str_replace("\\","/",$filePath);
	if (file_exists($filePath)) unlink($filePath);
	
	$sql = ' SELECT CONF_LOGO FROM evento_configuracao WHERE EVEN_ID = '.$this->getEVEN_ID() ;
	//echo $sql."<br>";
	$result = $this->database->query($sql);
	$result = $this->database->result;
	$row = mysql_fetch_object($result);
	//echo $row->CONF_LOGO;break;
	
	$file = fopen($filePath,"w");
	fwrite($file,$row->CONF_LOGO);

}

} // class : end

?>