<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        evento
* GENERATION DATE:  12.10.2006
* CLASS FILE:       C:\Develop\xampp\htdocs\sql_class_generator/generated_classes/class.evento.php
* FOR MYSQL TABLE:  evento
* FOR MYSQL DB:     officemkt
* -------------------------------------------------------
* CODE GENERATED BY:
* MY PHP-MYSQL-CLASS GENERATOR
* from: >> www.voegeli.li >> (download for free!)
* -------------------------------------------------------
*
*/

include_once("class.database.php");

// **********************
// CLASS DECLARATION
// **********************

class Evento
{ // class : begin


// **********************
// ATTRIBUTE DECLARATION
// **********************

private $ID;   // KEY ATTR. WITH AUTOINCREMENT

private $ORGA_ID;   // (normal Attribute)
private $NOME;   // (normal Attribute)
private $INICIO;   // (normal Attribute)
private $FIM;   // (normal Attribute)
private $LOCAL;   // (normal Attribute)
private $TIPO;   // (normal Attribute)
private $PATROC;   // (normal Attribute)
private $ESPACO;   // (normal Attribute)
private $APOIO;   // (normal Attribute)
private $QTD_PART;   // (normal Attribute)
private $QTD_SALAS;   // (normal Attribute)
private $QTD_TRAB;   // (normal Attribute)
private $OBS;   // (normal Attribute)

private $database; // Instance of class database


// **********************
// CONSTRUCTOR METHOD
// **********************

function Evento()
{

$this->database = new Database();

}


// **********************
// GETTER METHODS
// **********************


function getID()
{
return $this->ID;
}

function getNOME()
{
return $this->NOME;
}

function getORGA_ID()
{
return $this->ORGA_ID;
}

function getINICIO()
{
return $this->INICIO;
}

function getFIM()
{
return $this->FIM;
}

function getLOCAL()
{
return $this->LOCAL;
}

function getTIPO()
{
return $this->TIPO;
}

function getQTD_TRAB()
{
return $this->QTD_TRAB;
}

function getPATROC()
{
return $this->PATROC;
}

function getESPACO()
{
return $this->ESPACO;
}

function getAPOIO()
{
return $this->APOIO;
}

function getQTD_PART()
{
return $this->QTD_PART;
}

function getQTD_SALAS()
{
return $this->QTD_SALAS;
}

function getOBS()
{
return $this->OBS;
}

// **********************
// SETTER METHODS
// **********************


function setID($val)
{
$this->ID =  $val;
}

function setNOME($val)
{
$this->NOME =  $val;
}

function setORGA_ID($val)
{
$this->ORGA_ID =  $val;
}

function setINICIO($val)
{
$this->INICIO =  $val;
}

function setFIM($val)
{
$this->FIM =  $val;
}

function setLOCAL($val)
{
$this->LOCAL =  $val;
}

function setTIPO($val)
{
$this->TIPO =  $val;
}

function setPATROC($val)
{
$this->PATROC =  $val;
}

function setESPACO($val)
{
$this->ESPACO =  $val;
}

function setAPOIO($val)
{
$this->APOIO =  $val;
}

function setQTD_PART($val)
{
$this->QTD_PART =  $val;
}

function setQTD_SALAS($val)
{
$this->QTD_SALAS =  $val;
}

function setQTD_TRAB($val)
{
$this->QTD_TRAB =  $val;
}

function setOBS($val)
{
$this->OBS =  $val;
}

// **********************
// SELECT METHOD / LOAD
// **********************

function select($id)
{

$sql =  "SELECT * FROM evento WHERE EVEN_ID = $id;";
$result =  $this->database->query($sql);
$result = $this->database->result;
$row = mysql_fetch_object($result);


$this->ID = $row->EVEN_ID;

$this->NOME = $row->EVEN_NOME;

$this->ORGA_ID = $row->ORGA_ID;

$this->INICIO = $row->EVEN_INICIO;

$this->FIM = $row->EVEN_FIM;

$this->LOCAL = $row->EVEN_LOCAL;

$this->TIPO = $row->EVEN_TIPO;

$this->PATROC = $row->EVEN_PATROC;

$this->ESPACO = $row->EVEN_ESPACO;

$this->APOIO = $row->EVEN_APOIO;

$this->QTD_PART = $row->EVEN_QTD_PART;

$this->QTD_SALAS = $row->EVEN_QTD_SALAS;

$this->QTD_TRAB = $row->EVEN_QTD_TRAB;

$this->OBS = $row->EVEN_OBS;

}

// **********************
// DELETE
// **********************

function delete($id)
{
$sql = "DELETE FROM evento WHERE EVEN_ID = $id;";
$result = $this->database->query($sql);

}

// **********************
// SAVE
// **********************

function save() {
	if ($this->ID != null) {
		$this->update($this->ID);
	} else {
		$this->insert();
	}
}

// **********************
// INSERT
// **********************

function insert()
{
$this->ID = ""; // clear key for autoincrement

$sql = "INSERT INTO evento ( ORGA_ID,EVEN_NOME,EVEN_INICIO,EVEN_FIM,EVEN_LOCAL,EVEN_TIPO,EVEN_PATROC,EVEN_ESPACO,EVEN_APOIO,EVEN_QTD_PART,EVEN_QTD_SALAS,EVEN_QTD_TRAB,EVEN_OBS ) VALUES ( '$this->ORGA_ID','$this->NOME','$this->INICIO','$this->FIM','$this->LOCAL','$this->TIPO','$this->PATROC','$this->ESPACO','$this->APOIO','$this->QTD_PART','$this->QTD_SALAS','$this->QTD_TRAB','$this->OBS' )";
$result = $this->database->query($sql);
$this->ID = mysql_insert_id($this->database->link);

}

// **********************
// UPDATE
// **********************

function update($id)
{



$sql = " UPDATE evento SET  ORGA_ID = '$this->ORGA_ID',EVEN_NOME = '$this->NOME',EVEN_INICIO = '$this->INICIO',EVEN_FIM = '$this->FIM',EVEN_LOCAL = '$this->LOCAL',EVEN_TIPO = '$this->TIPO',EVEN_PATROC = '$this->PATROC',EVEN_ESPACO = '$this->ESPACO',EVEN_APOIO = '$this->APOIO',EVEN_QTD_PART = '$this->QTD_PART',EVEN_QTD_SALAS = '$this->QTD_SALAS',EVEN_QTD_TRAB = '$this->QTD_TRAB',EVEN_OBS = '$this->OBS' WHERE EVEN_ID = $id ";

$result = $this->database->query($sql);



}


} // class : end

?>