<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        conteudo
* GENERATION DATE:  04.12.2006
* CLASS FILE:       C:\Develop\xampp\htdocs\sql_class_generator/generated_classes/class.conteudo.php
* FOR MYSQL TABLE:  conteudo
* FOR MYSQL DB:     captar
* -------------------------------------------------------
* CODE GENERATED BY:
* MY PHP-MYSQL-CLASS GENERATOR
* from: >> www.voegeli.li >> (download for free!)
* -------------------------------------------------------
*
*/

include_once("class.database.php");

// **********************
// CLASS DECLARATION
// **********************

class Conteudo { // class : begin


// **********************
// ATTRIBUTE DECLARATION
// **********************

var $Id;   // KEY ATTR. WITH AUTOINCREMENT

var $Titulo;   // (normal Attribute)
var $Corpo;   // (normal Attribute)
var $Data;   // (normal Attribute)
var $ImagemA;   // (normal Attribute)
var $ImagemB;   // (normal Attribute)
var $ImagemC;   // (normal Attribute)
var $ImagemD;   // (normal Attribute)
var $ImagemE;   // (normal Attribute)
var $ImagemF;   // (normal Attribute)
var $ImagemG;   // (normal Attribute)
var $ImagemH;   // (normal Attribute)
var $ImagemI;   // (normal Attribute)
var $ImagemJ;   // (normal Attribute)
var $ImagemK;   // (normal Attribute)
var $LegendaA;   // (normal Attribute)
var $LegendaB;   // (normal Attribute)
var $LegendaC;   // (normal Attribute)
var $LegendaD;   // (normal Attribute)
var $LegendaE;   // (normal Attribute)
var $LegendaF;   // (normal Attribute)
var $LegendaG;   // (normal Attribute)
var $LegendaH;   // (normal Attribute)
var $LegendaI;   // (normal Attribute)
var $LegendaJ;   // (normal Attribute)
var $LegendaK;   // (normal Attribute)
var $Link;   // (normal Attribute)
var $Campo1;   // (normal Attribute)
var $Campo2;   // (normal Attribute)
var $Campo3;   // (normal Attribute)
var $DataCadastro;   // (normal Attribute)
var $DataModificacao;   // (normal Attribute)
var $Status;   // (normal Attribute)
var $Tipo;   // (normal Attribute)
var $Ordem;   // (normal Attribute)
var $Idioma;   // (normal Attribute)

var $database; // Instance of class database


var $TIPO_NOTICIA = 1;
var $TIPO_CASE = 2;

var $IDIOMA_PT = 1;
var $IDIOMA_ES = 2;

// **********************
// CONSTRUCTOR METHOD
// **********************

function conteudo() {

	$this->database = new Database();

}


// **********************
// GETTER METHODS
// **********************


function getId() {
return $this->Id;
}

function getTitulo() {
return $this->Titulo;
}

function getCorpo() {
return $this->Corpo;
}

function getData() {
	return $this->Data;
}

function getImagemA() {
return $this->ImagemA;
}

function getImagemB() {
return $this->ImagemB;
}

function getImagemC() {
return $this->ImagemC;
}

function getImagemD() {
return $this->ImagemD;
}

function getImagemE() {
return $this->ImagemE;
}

function getImagemF() {
return $this->ImagemF;
}

function getImagemG() {
return $this->ImagemF;
}

function getImagemH() {
return $this->ImagemF;
}

function getImagemI() {
return $this->ImagemF;
}

function getImagemJ() {
return $this->ImagemF;
}

function getImagemK() {
return $this->ImagemF;
}

function getLegendaA() {
return $this->LegendaA;
}

function getLegendaB() {
return $this->LegendaB;
}

function getLegendaC() {
return $this->LegendaC;
}

function getLegendaD() {
return $this->LegendaD;
}

function getLegendaE() {
return $this->LegendaE;
}

function getLegendaF() {
return $this->LegendaF;
}

function getLegendaG() {
return $this->LegendaF;
}

function getLegendaH() {
return $this->LegendaF;
}

function getLegendaI() {
return $this->LegendaF;
}

function getLegendaJ() {
return $this->LegendaF;
}

function getLegendaK() {
return $this->LegendaF;
}

function getLink() {
return $this->Link;
}

function getCampo1() {
return $this->Campo1;
}

function getCampo2() {
return $this->Campo2;
}

function getCampo3() {
return $this->Campo3;
}

function getDataCadastro() {
return $this->DataCadastro;
}

function getDataModificacao() {
return $this->DataModificacao;
}

function getStatus() {
return $this->Status;
}

function getTipo() {
return $this->Tipo;
}

function getOrdem() {
return $this->Ordem;
}

function getIdioma() {
return $this->Idioma;
}

// **********************
// SETTER METHODS
// **********************


function setId($val) {
$this->Id =  $val;
}

function setTitulo($val) {
$this->Titulo =  $val;
}

function setCorpo($val) {
$this->Corpo =  $val;
}

function setData($val) {
$this->Data =  $val;
}

function setImagemA($val) {
$this->ImagemA =  $val;
}

function setImagemB($val) {
$this->ImagemB =  $val;
}

function setImagemC($val) {
$this->ImagemC =  $val;
}

function setImagemD($val) {
$this->ImagemD =  $val;
}

function setImagemE($val) {
$this->ImagemE =  $val;
}

function setImagemF($val) {
$this->ImagemF =  $val;
}

function setImagemG($val) {
$this->ImagemF =  $val;
}

function setImagemH($val) {
$this->ImagemF =  $val;
}

function setImagemI($val) {
$this->ImagemF =  $val;
}

function setImagemJ($val) {
$this->ImagemF =  $val;
}

function setImagemK($val) {
$this->ImagemF =  $val;
}

function setLegendaA($val) {
$this->LegendaA =  $val;
}

function setLegendaB($val) {
$this->LegendaB =  $val;
}

function setLegendaC($val) {
$this->LegendaC =  $val;
}

function setLegendaD($val) {
$this->LegendaD =  $val;
}

function setLegendaE($val) {
$this->LegendaE =  $val;
}

function setLegendaF($val) {
$this->LegendaF =  $val;
}

function setLegendaG($val) {
$this->LegendaF =  $val;
}

function setLegendaH($val) {
$this->LegendaF =  $val;
}

function setLegendaI($val) {
$this->LegendaF =  $val;
}

function setLegendaJ($val) {
$this->LegendaF =  $val;
}

function setLegendaK($val) {
$this->LegendaF =  $val;
}

function setLink($val) {
$this->Link =  $val;
}

function setCampo1($val) {
$this->Campo1 =  $val;
}

function setCampo2($val) {
$this->Campo2 =  $val;
}

function setCampo3($val) {
$this->Campo3 =  $val;
}

function setDataCadastro($val) {
$this->DataCadastro =  $val;
}

function setDataModificacao($val) {
$this->DataModificacao =  $val;
}

function setStatus($val) {
$this->Status =  $val;
}

function setTipo($val) {
$this->Tipo =  $val;
}

function setOrdem($val) {
$this->Ordem =  $val;
}

function setIdioma($val) {
$this->Idioma =  $val; 
}

// **********************
// SELECT METHOD / LOAD
// **********************

function select($id) {

$sql =  "SELECT * FROM conteudo WHERE Id = $id;";
$result =  $this->database->query($sql);
$result = $this->database->result;
$row = mysql_fetch_object($result);


$this->Id = $row->Id;
$this->Titulo = $row->Titulo;
$this->Corpo = $row->Corpo;
$this->Data = $row->Data;
$this->ImagemA = $row->ImagemA;
$this->ImagemB = $row->ImagemB;
$this->ImagemC = $row->ImagemC;
$this->ImagemD = $row->ImagemD;
$this->ImagemE = $row->ImagemE;
$this->ImagemF = $row->ImagemF;
$this->ImagemG = $row->ImagemG;
$this->ImagemH = $row->ImagemH;
$this->ImagemI = $row->ImagemI;
$this->ImagemJ = $row->ImagemJ;
$this->ImagemK = $row->ImagemK;
$this->LegendaA = $row->LegendaA;
$this->LegendaB = $row->LegendaB;
$this->LegendaC = $row->LegendaC;
$this->LegendaD = $row->LegendaD;
$this->LegendaE = $row->LegendaE;
$this->LegendaF = $row->LegendaF;
$this->LegendaG = $row->LegendaG;
$this->LegendaH = $row->LegendaH;
$this->LegendaI = $row->LegendaI;
$this->LegendaJ = $row->LegendaJ;
$this->LegendaK = $row->LegendaK;
$this->Link = $row->Link;
$this->Campo1 = $row->Campo1;
$this->Campo2 = $row->Campo2;
$this->Campo3 = $row->Campo3;
$this->DataCadastro = $row->DataCadastro;
$this->DataModificacao = $row->DataModificacao;
$this->Status = $row->Status;
$this->Tipo = $row->Tipo;
$this->Ordem = $row->Ordem;
$this->Idioma = $row->Idioma;

}

// **********************
// DELETE
// **********************

function delete($id)
{
$sql = "DELETE FROM conteudo WHERE Id = $id;";
$result = $this->database->query($sql);

}

// **********************
// SAVE
// **********************

function save() {
	if ($this->Id != null) {
		$this->update($this->Id);
	} else {
		$this->insert();
	}
}

// **********************
// INSERT
// **********************

function insert() {
	$this->Id = ""; // clear key for autoincrement
	
	$sql = "INSERT INTO conteudo ( Titulo,Corpo,Data,ImagemA,ImagemB,ImagemC,ImagemD,ImagemE,ImagemF,ImagemG,ImagemH,ImagemI,ImagemJ,ImagemK,LegendaA,LegendaB,LegendaC,LegendaD,LegendaE,LegendaF,LegendaG,LegendaH,LegendaI,LegendaJ,LegendaK,Link,Campo1,Campo2,Campo3,DataCadastro,DataModificacao,Status,Tipo,Ordem,Idioma ) VALUES ( '$this->Titulo','$this->Corpo','$this->Data','$this->ImagemA','$this->ImagemB','$this->ImagemC','$this->ImagemD','$this->ImagemE','$this->ImagemF','$this->ImagemG','$this->ImagemH','$this->ImagemI','$this->ImagemJ','$this->ImagemK','$this->LegendaA','$this->LegendaB','$this->LegendaC','$this->LegendaD','$this->LegendaE','$this->LegendaF','$this->LegendaG','$this->LegendaH','$this->LegendaI','$this->LegendaJ','$this->LegendaK','$this->Link','$this->Campo1','$this->Campo2','$this->Campo3','$this->DataCadastro','$this->DataModificacao','$this->Status','$this->Tipo','$this->Ordem','$this->Idioma' )";
	$result = $this->database->query($sql);
	$this->Id = mysql_insert_id($this->database->link);

}

// **********************
// UPDATE
// **********************

function update($id) {

	$sql = " UPDATE conteudo SET  Titulo = '$this->Titulo',Corpo = '$this->Corpo',Data = '$this->Data',ImagemA = '$this->ImagemA',ImagemB = '$this->ImagemB',ImagemC = '$this->ImagemC',ImagemD = '$this->ImagemD',ImagemE = '$this->ImagemE',ImagemF = '$this->ImagemF',ImagemG = '$this->ImagemG',ImagemH = '$this->ImagemH',ImagemI = '$this->ImagemI',ImagemJ = '$this->ImagemJ',ImagemK = '$this->ImagemK',LegendaA = '$this->LegendaA',LegendaB = '$this->LegendaB',LegendaC = '$this->LegendaC',LegendaD = '$this->LegendaD',LegendaE = '$this->LegendaE',LegendaF = '$this->LegendaF',LegendaG = '$this->LegendaG',LegendaH = '$this->LegendaH',LegendaI = '$this->LegendaI',LegendaJ = '$this->LegendaJ',LegendaK = '$this->LegendaK',Link = '$this->Link',Campo1 = '$this->Campo1',Campo2 = '$this->Campo2',Campo3 = '$this->Campo3',DataCadastro = '$this->DataCadastro',DataModificacao = '$this->DataModificacao',Status = '$this->Status',Tipo = '$this->Tipo',Ordem = '$this->Ordem',Idioma = '$this->Idioma' WHERE Id = $id ";
	$result = $this->database->query($sql);

}


} // class : end

?>