<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        organizacao
* GENERATION DATE:  12.10.2006
* CLASS FILE:       C:\Develop\xampp\htdocs\sql_class_generator/generated_classes/class.organizacao.php
* FOR MYSQL TABLE:  organizacao
* FOR MYSQL DB:     officemkt
* -------------------------------------------------------
* CODE GENERATED BY:
* MY PHP-MYSQL-CLASS GENERATOR
* from: >> www.voegeli.li >> (download for free!)
* -------------------------------------------------------
*
*/

include_once("class.database.php");

// **********************
// CLASS DECLARATION
// **********************

class Organizacao
{ // class : begin


// **********************
// ATTRIBUTE DECLARATION
// **********************

private $ID;   // KEY ATTR. WITH AUTOINCREMENT

private $NOME;   // (normal Attribute)
private $RAZAO;   // (normal Attribute)
private $CNPJ;   // (normal Attribute)
private $IE;   // (normal Attribute)
private $IM;   // (normal Attribute)
private $SITE;   // (normal Attribute)
private $FONE;   // (normal Attribute)
private $FAX;   // (normal Attribute)
private $ENDERECO;   // (normal Attribute)
private $BAIRRO;   // (normal Attribute)
private $CIDADE;   // (normal Attribute)
private $CEP;   // (normal Attribute)
private $ESTADO;   // (normal Attribute)
private $PAIS;   // (normal Attribute)
private $OBS;   // (normal Attribute)

private $database; // Instance of class database


// **********************
// CONSTRUCTOR METHOD
// **********************

function Organizacao()
{

$this->database = new Database();

}


// **********************
// GETTER METHODS
// **********************


function getID()
{
return $this->ID;
}

function getNOME()
{
return $this->NOME;
}

function getRAZAO()
{
return $this->RAZAO;
}

function getCNPJ()
{
return $this->CNPJ;
}

function getIM()
{
return $this->IM;
}

function getIE()
{
return $this->IE;
}

function getSITE()
{
return $this->SITE;
}

function getFONE()
{
return $this->FONE;
}

function getFAX()
{
return $this->FAX;
}

function getENDERECO()
{
return $this->ENDERECO;
}

function getBAIRRO()
{
return $this->BAIRRO;
}

function getCIDADE()
{
return $this->CIDADE;
}

function getCEP()
{
return $this->CEP;
}

function getESTADO()
{
return $this->ESTADO;
}

function getPAIS()
{
return $this->PAIS;
}

function getOBS()
{
return $this->OBS;
}

// **********************
// SETTER METHODS
// **********************


function setID($val)
{
$this->ID =  $val;
}

function setNOME($val)
{
$this->NOME =  $val;
}

function setRAZAO($val)
{
$this->RAZAO =  $val;
}

function setCNPJ($val)
{
$this->CNPJ =  $val;
}

function setIE($val)
{
$this->IE =  $val;
}

function setIM($val)
{
$this->IM =  $val;
}

function setSITE($val)
{
$this->SITE =  $val;
}

function setFONE($val)
{
$this->FONE =  $val;
}

function setFAX($val)
{
$this->FAX =  $val;
}

function setENDERECO($val)
{
$this->ENDERECO =  $val;
}

function setBAIRRO($val)
{
$this->BAIRRO =  $val;
}

function setCIDADE($val)
{
$this->CIDADE =  $val;
}

function setCEP($val)
{
$this->CEP =  $val;
}

function setESTADO($val)
{
$this->ESTADO =  $val;
}

function setPAIS($val)
{
$this->PAIS =  $val;
}

function setOBS($val)
{
$this->OBS =  $val;
}

// **********************
// SELECT METHOD / LOAD
// **********************

function select($id)
{

$sql =  "SELECT * FROM organizacao WHERE ORGA_ID = $id;";
$result =  $this->database->query($sql);
$result = $this->database->result;
$row = mysql_fetch_object($result);


$this->ID = $row->ORGA_ID;

$this->NOME = $row->ORGA_NOME;

$this->RAZAO = $row->ORGA_RAZAO;

$this->CNPJ = $row->ORGA_CNPJ;

$this->IE = $row->ORGA_IE;

$this->IM = $row->ORGA_IM;

$this->SITE = $row->ORGA_SITE;

$this->FONE = $row->ORGA_FONE;

$this->FAX = $row->ORGA_FAX;

$this->ENDERECO = $row->ORGA_ENDERECO;

$this->BAIRRO = $row->ORGA_BAIRRO;

$this->CIDADE = $row->ORGA_CIDADE;

$this->CEP = $row->ORGA_CEP;

$this->ESTADO = $row->ORGA_ESTADO;

$this->PAIS = $row->ORGA_PAIS;

$this->OBS = $row->ORGA_OBS;

}

// **********************
// DELETE
// **********************

function delete($id)
{
$sql = "DELETE FROM organizacao WHERE ORGA_ID = $id;";
$result = $this->database->query($sql);

}

// **********************
// SAVE
// **********************

function save() {
	if ($this->ID != null) {
		$this->update($this->ID);
	} else {
		$this->insert();
	}
}


// **********************
// INSERT
// **********************

function insert()
{
$this->ID = ""; // clear key for autoincrement

$sql = "INSERT INTO organizacao ( ORGA_NOME,ORGA_RAZAO,ORGA_CNPJ,ORGA_IE,ORGA_IM,ORGA_SITE,ORGA_FONE,ORGA_FAX,ORGA_ENDERECO,ORGA_BAIRRO,ORGA_CIDADE,ORGA_CEP,ORGA_ESTADO,ORGA_PAIS,ORGA_OBS ) VALUES ( '$this->NOME','$this->RAZAO','$this->CNPJ','$this->IE','$this->IM','$this->SITE','$this->FONE','$this->FAX','$this->ENDERECO','$this->BAIRRO','$this->CIDADE','$this->CEP','$this->ESTADO','$this->PAIS','$this->OBS' )";
$result = $this->database->query($sql);
$this->ID = mysql_insert_id($this->database->link);

}

// **********************
// UPDATE
// **********************

function update($id)
{



$sql = " UPDATE organizacao SET  ORGA_NOME = '$this->NOME',ORGA_RAZAO = '$this->RAZAO',ORGA_CNPJ = '$this->CNPJ',ORGA_IE = '$this->IE',ORGA_IM = '$this->IM',ORGA_SITE = '$this->SITE',ORGA_FONE = '$this->FONE',ORGA_FAX = '$this->FAX',ORGA_ENDERECO = '$this->ENDERECO',ORGA_BAIRRO = '$this->BAIRRO',ORGA_CIDADE = '$this->CIDADE',ORGA_CEP = '$this->CEP',ORGA_ESTADO = '$this->ESTADO',ORGA_PAIS = '$this->PAIS',ORGA_OBS = '$this->OBS' WHERE ORGA_ID = $id ";

$result = $this->database->query($sql);



}


} // class : end

?>