<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        contato
* GENERATION DATE:  12.10.2006
* CLASS FILE:       C:\Develop\xampp\htdocs\sql_class_generator/generated_classes/class.contato.php
* FOR MYSQL TABLE:  contato
* FOR MYSQL DB:     officemkt
* -------------------------------------------------------
* CODE GENERATED BY:
* MY PHP-MYSQL-CLASS GENERATOR
* from: >> www.voegeli.li >> (download for free!)
* -------------------------------------------------------
*
*/

include_once("class.database.php");

// **********************
// CLASS DECLARATION
// **********************

class Contato
{ // class : begin


// **********************
// ATTRIBUTE DECLARATION
// **********************

private $ID;   // KEY ATTR. WITH AUTOINCREMENT

private $ORGA_ID;   // (normal Attribute)
private $EVEN_ID;   // (normal Attribute)
private $USUA_ID;   // (normal Attribute)
private $DATA;   // (normal Attribute)
private $TIPO;   // (normal Attribute)
private $OBS;   // (normal Attribute)

private $database; // Instance of class database


// **********************
// CONSTRUCTOR METHOD
// **********************

function Contato()
{

$this->database = new Database();

}


// **********************
// GETTER METHODS
// **********************


function getID()
{
return $this->ID;
}

function getORGA_ID()
{
return $this->ORGA_ID;
}

function getEVEN_ID()
{
return $this->EVEN_ID;
}

function getUSUA_ID()
{
return $this->USUA_ID;
}

function getDATA()
{
return $this->DATA;
}

function getTIPO()
{
return $this->TIPO;
}

function getOBS()
{
return $this->OBS;
}

// **********************
// SETTER METHODS
// **********************


function setID($val)
{
$this->ID =  $val;
}

function setORGA_ID($val)
{
$this->ORGA_ID =  $val;
}

function setEVEN_ID($val)
{
$this->EVEN_ID =  $val;
}

function setUSUA_ID($val)
{
$this->USUA_ID =  $val;
}

function setDATA($val)
{
$this->DATA =  $val;
}

function setTIPO($val)
{
$this->TIPO =  $val;
}

function setOBS($val)
{
$this->OBS =  $val;
}

// **********************
// SELECT METHOD / LOAD
// **********************

function select($id)
{

$sql =  "SELECT * FROM contato WHERE CONT_ID = $id;";
$result =  $this->database->query($sql);
$result = $this->database->result;
$row = mysql_fetch_object($result);


$this->ID = $row->CONT_ID;
$this->ORGA_ID = $row->ORGA_ID;
$this->EVEN_ID = $row->EVEN_ID;
$this->USUA_ID = $row->USUA_ID;
$this->DATA = $row->CONT_DATA;
$this->TIPO = $row->CONT_TIPO;
$this->OBS = $row->CONT_OBS;

}

// **********************
// DELETE
// **********************

function delete($id)
{
$sql = "DELETE FROM contato WHERE CONT_ID = $id;";
$result = $this->database->query($sql);

}

// **********************
// SAVE
// **********************

function save() {
	if ($this->ID != null) {
		$this->update($this->ID);
	} else {
		$this->insert();
	}
}
// **********************
// INSERT
// **********************

function insert()
{
$this->ID = ""; // clear key for autoincrement

$sql = "INSERT INTO contato ( ORGA_ID,EVEN_ID,USUA_ID,CONT_DATA,CONT_TIPO,CONT_OBS ) VALUES ( '$this->ORGA_ID','$this->EVEN_ID','$this->USUA_ID','$this->DATA','$this->TIPO','$this->OBS' )";
$result = $this->database->query($sql);
$this->ID = mysql_insert_id($this->database->link);

}

// **********************
// UPDATE
// **********************

function update($id)
{



$sql = " UPDATE contato SET  ORGA_ID = '$this->ORGA_ID',EVEN_ID = '$this->EVEN_ID',USUA_ID = '$this->USUA_ID',CONT_DATA = '$this->DATA',CONT_TIPO = '$this->TIPO',CONT_OBS = '$this->OBS' WHERE CONT_ID = $id ";

$result = $this->database->query($sql);



}


} // class : end

?>