
<!-- begin of generated class -->
<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        assobrafir
* GENERATION DATE:  30.04.2009
* CLASS FILE:       C:\wamp\www\class.generator\mygenerator/generated_classes/class.assobrafir.php
* FOR MYSQL TABLE:  assobrafir_trab
* FOR MYSQL DB:     eventoonline
* -------------------------------------------------------
* CODE GENERATED BY:
* MY PHP-MYSQL-CLASS GENERATOR
* from: >> www.voegeli.li >> (download for free!)
* -------------------------------------------------------
*
*/

include_once("class.database.php");

// **********************
// CLASS DECLARATION
// **********************

class Imc
{ // class : begin


// **********************
// ATTRIBUTE DECLARATION
// **********************

var $imc_trab_id;   // KEY ATTR. WITH AUTOINCREMENT

var $imc_trab_inscricao_id;   // (normal Attribute)
var $imc_trab_key;   // (normal Attribute)
var $imc_trab_login;   // (normal Attribute)
var $imc_trab_password;   // (normal Attribute)
var $imc_trab_trabalhos;   // (normal Attribute)

var $database; // Instance of class database


// **********************
// CONSTRUCTOR METHOD
// **********************

function imc()
{

$this->database = new Database();

}


// **********************
// GETTER METHODS
// **********************


function getimc_trab_id()
{
return $this->imc_trab_id;
}

function getimc_trab_inscricao_id()
{
return $this->imc_trab_inscricao_id;
}

function getimc_trab_key()
{
return $this->imc_trab_key;
}

function getimc_trab_login()
{
return $this->imc_trab_login;
}

function getimc_trab_password()
{
return $this->imc_trab_password;
}

function getimc_trab_trabalhos()
{
return $this->imc_trab_trabalhos;
}

// **********************
// SETTER METHODS
// **********************


function setimc_trab_id($val)
{
$this->imc_trab_id =  $val;
}

function setimc_trab_inscricao_id($val)
{
$this->imc_trab_inscricao_id =  $val;
}

function setimc_trab_key($val)
{
$this->imc_trab_key =  $val;
}

function setimc_trab_login($val)
{
$this->imc_trab_login =  $val;
}

function setimc_trab_password($val)
{
$this->imc_trab_password =  $val;
}

function setimc_trab_trabalhos($val)
{
$this->imc_trab_trabalhos =  $val;
}

// **********************
// SELECT METHOD / LOAD
// **********************

function select($id)
{

$sql =  "SELECT * FROM imc_trab WHERE imc_trab_id = $id;";
$result =  $this->database->query($sql);
$result = $this->database->result;
$row = mysql_fetch_object($result);


$this->imc_trab_id = $row->imc_trab_id;

$this->imc_trab_inscricao_id = $row->imc_trab_inscricao_id;

$this->imc_trab_key = $row->imc_trab_key;

$this->imc_trab_login = $row->imc_trab_login;

$this->imc_trab_password = $row->imc_trab_password;

$this->imc_trab_trabalhos = $row->imc_trab_trabalhos;

}

// **********************
// DELETE
// **********************

function delete($id)
{
$sql = "DELETE FROM imc_trab WHERE imc_trab_id = $id;";
$result = $this->database->query($sql);

}

// **********************
// INSERT
// **********************

function insert()
{
$this->assobrafir_trab_id = ""; // clear key for autoincrement

$sql = "INSERT INTO imc_trab ( imc_trab_inscricao_id,imc_trab_key,imc_trab_login,imc_trab_password,imc_trab_trabalhos ) VALUES ( '$this->imc_trab_inscricao_id','$this->imc_trab_key','$this->imc_trab_login','$this->imc_trab_password','$this->imc_trab_trabalhos' )";
$result = $this->database->query($sql);
$this->assobrafir_trab_id = mysql_insert_id($this->database->link);

}

// **********************
// UPDATE
// **********************

function update($id)
{



$sql = " UPDATE imc_trab SET  imc_trab_inscricao_id = '$this->imc_trab_inscricao_id',imc_trab_key = '$this->imc_trab_key',imc_trab_login = '$this->imc_trab_login',imc_trab_password = '$this->imc_trab_password',imc_trab_trabalhos = '$this->imc_trab_trabalhos' WHERE imc_trab_id = $id ";

$result = $this->database->query($sql);



}


} // class : end

?>
<!-- end of generated class -->
